/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.eckey;

import java.security.SignatureException;

import org.eckey.core.ECKey;

public class App {
    public static void main(String[] args) {
        ECKey sm2key = new ECKey();
        System.out.println(sm2key.GetPrivate());
        System.out.println(sm2key.GetPublic());

        String message = "Hello World!";
        // 内部对String做sha256 hash后签名
        String sigStr = sm2key.sign(message);
        System.out.println(sigStr);

        try {
            sm2key.verifyMessage(message.getBytes(), sigStr);
        } catch (SignatureException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        try {
            String recoverKey = ECKey.signedMessageToKey(message.getBytes(), sigStr);
            System.out.println(recoverKey);
        } catch (SignatureException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }
}
